---
title: "Make a GitHub repository (40 minutes)"
---

::: {.callout-warning}
We request that everyone use the GitHub browser interface. If you choose not to, be
prepared to support your group if issues like merge conflicts arise. See <link to
CryoCloud Git gotchas> for details on using Git in CryoCloud.

_TODO: CryoCloud link. Ask Tasha how we should handle auth_
:::

## ✨ Create repository for your group

Pick a person in your group to "drive" a screen share and set up your group repository.
We suggest someone who has never created a GitHub repository before.

Create a new GitHub repository under the `qgreenland-workshop-2023-researcher`
organization.

Your repository should be named with convention: _TODO: Convention!_


## 📂 Add some content

* Add the notebook your team produced during the
  [Data Inspection](./data-inspection-with-jupyterlab/index.qmd) exercise to
  your repository.
* Add a `README.md` file:
    * List your team members by name.
    * Identify the dataset your group has chosen to explore.
* [Turn on GitHub
  Discussions](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository)
  for your group repository. Use this space for asynchronous discussions within your
  group during (or after!) the workshop.


## ✨ Create your personal profile repository

Follow [GitHub's
instructions](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme#adding-a-profile-readme)
to create a profile repository with a profile README.

You may want to use your introductory post to [GitHub
Discussions](https://github.com/orgs/qgreenland-workshop-2023-researcher/discussions/categories/introductions)
to inspire the contents of this README.

When you're done, you should be able to navigate to `https://github.com/<your-username>`
and see your new content displayed!


## ⏱️ Finished early?

* Check out our [continued learning](/content/continued-learning.qmd#gitgithub)
  resources!


## TODO

* Figure out how permissions will be handled.
* Repository naming convention.
* Should there be another deliverable here? A GitHub discussion? A reflection on the
  day?
