<!-- vim: set ft=markdown: -->

# Intro to JupyterHub

## Intro to JupyterHub

* CryoCloud
    * JupyterHub: <https://hub.cryointhecloud.com>
    * Website: <https://book.cryointhecloud.com>

* Log in to CryoCloud JupyterHub with your GitHub username
    * Important: select a _small_ server!
    * Your JupyterLab is dedicated, _not_ shared!

* _Please log out at the end of each day using `File > Log Out`!_

::: {.notes}
* JupyterHub is a system for creating many JupyterLabs, e.g. for classrooms
* JupyterLab is not shared!
    * Other attendees can't see your files (except those in "shared" dir)
    * Your computations won't slow down anyone else's
* Log out at the end of each day to save on cloud costs.
    * Any files you've created will remain next time you log in.
:::


## What can I do in my JupyterLab?

Almost anything you can do on your laptop!

JupyterLab is meant to be a human interface to computation resources.


## What can I do in my JupyterLab?

### File Manager

* Drag & drop from your desktop
* Open many types of files and get a useful display
    * CSV will display as table
    * GeoJSON will display on a map
    * Images will open with an image viewer


## What can I do in my JupyterLab?

### Applications

* Terminal
    * `conda install <package>` / `mamba install <package>`
* Desktop / QGIS
    * Has access to the files in your JupyterLab
* Jupyter Notebooks

::: {.notes}
Conda and Mamba are already installed, and a `notebook` environment is pre-created. Use
`conda`/`mamba` commands to install Python dependencies into the `notebook` environment.
:::


## Jupyter Notebooks

* A tool for [Literate Programming](https://en.wikipedia.org/wiki/Literate_programming)
    * Showing your work
    * Tracking provenance
    * Telling a story
* See also:
    * Quarto
    * JupyterBook
    * _TODO: Others?_


## Jupyter Notebook demo

* Walk through running an example notebook and viewing its output in QGIS?
    * _TODO: Generate the example notebook._
    * _TODO: Maybe programmatically generate a random distribution of points over an
      area in Greenland (e.g. use the extent of "Greenland coastlines 2017" layer as the
      x/y extents for random-number generation, then filter those random coordinates
      using the "Greenland coastlines 2017" layer)._
    * _TODO: Maybe filter the "Place names database" layer by:_
        * Random sample
        * Maximum of a particular attribute
