# Ideas

* Include a break (or two) in each day's schedule. Break every hour? 90 minutes? How
  long to break?
* Resampling exercise?
* Consider having a "quiet" breakout room in Zoom for those who prefer to not talk while
  working.
* Consider adding some buffer time before and after break for things to run
  long. A longer break is better than a shorter break.
* Keep a timer/alarm for making sure we stay on target and don't miss the break.
* Encourage rotation of "driver" responsibility in breakout groups.
* Talk briefly about pair/group programming?
* Set expectation of group activities in application materials.
* Consider a sync service (e.g., `syncthing`) for sharing data between participants.
* Think about ways to encourage larger-group discussions following breakout rooms.
* Should we expect any attendees to be concerned about credit-sharing for
  analysis done during workshop? Should we note that any papers produced
  directly from ideas developed in this workshop should include a citation of
  QGreenland and the workshop small group as collaborators?
* Should we have a module about integrating GitHub with Zenodo to create DOIs?
* Consider discussion about how data are often organized on disk (granularity)

## Breakout room activity ideas

* What approaches to data introspection have you used / are you comfortable with?
    * What can you teach your teammates?
    * What can your teammates teach you?
* Discuss experiences with geospatial data



## Goal ideas

* Show data transformation provenance using Jupyter Notebooks
* Transparently share transformations and provenance using GitHub
