<!-- vim: set ft=markdown: -->

# Discussion: Review of Open Science (and data) principles

## Open Science is here this year, get used to it!

2023 is the [Federal Year of Open
    Science](https://www.whitehouse.gov/ostp/news-updates/2023/01/11/fact-sheet-biden-harris-administration-announces-new-actions-to-advance-open-and-equitable-research/)

### Initiatives and participating organizations:

:::: {.columns}
::: {.column width="50%"}
* <https://open.science.gov/>
* [NASA TOPS](https://science.nasa.gov/open-science/transform-to-open-science)
* [NASA
    SPD-41a](https://science.nasa.gov/science-red/s3fs-public/atoms/files/SMD-information-policy-SPD-41a.pdf)
* [NIST](https://www.nist.gov/open/year-open-science)
:::

::: {.column width="50%"}
* [NSF](https://www.nsf.gov/pubs/2023/nsf23053/nsf23053.jsp?org=NSF)
* USGS
* National Endowment for the Humanities
* ...and more!
:::
::::


## Value of version control and doing work "in the open"

* GitHub Discussions
* _TODO: Example Open Source research repositories?_


## Important data principles: [FAIR](https://www.go-fair.org/fair-principles/)

<!-- TODO: more links! -->
::: {.incremental .r-fit-text}
* **<u>F</u>**indable
    * "Metadata and data should be easy to find for both humans **and computers**."
* **<u>A</u>**ccessible
    * Metadata and data should be easy to acquire for both humans **and computers**.
* **<u>I</u>**nteroperable
    * Data should be easy to integrate with other data and software.
      <!-- Should we mention the utility of "self-describing" data formats here? -->
* **<u>R</u>**eusable
    * [Well-described](https://www.go-fair.org/fair-principles/r1-metadata-richly-described-plurality-accurate-relevant-attributes/),
      [licensed](https://www.go-fair.org/fair-principles/r1-1-metadata-released-clear-accessible-data-usage-license/),
      [provenance](https://www.go-fair.org/fair-principles/r1-2-metadata-associated-detailed-provenance/),
      [community standards](https://www.go-fair.org/fair-principles/r1-3-metadata-meet-domain-relevant-community-standards/)
:::


## Important data principles: [CARE](https://www.gida-global.org/care)

::: {.incremental .r-fit-text}
* **<u>C</u>**ollective Benefit
    * Data and the systems around them should strive to benefit Indigenous
      communities.
* **<u>A</u>**uthority to Control
    * Indigenous Peoples should have the right to govern their data and
      representations of their communities in data. Data collection efforts
      should include the participation of Indigenous communities.
* **<u>R</u>**esponsibility
    * Users of Indigenous data have the responsibility to share data in a way
      that supports Indigenous Peoples and culture.
* **<u>E</u>**thics
    * The rights and wellbeing of Indigenous Peoples should be the priority
      through all aspects of the data life-cycle.
:::


## Other data principles

* [FAIR4RS](https://www.rd-alliance.org/groups/fair-research-software-fair4rs-wg)
* [STREAM](https://www.itu.int/en/journal/002/Documents/ITU2018-12.pdf)?
  * _TODO: is this actually relevant? It's talking about data practices in the
    context of markets / commodification of data._
* [International Open Data Charter](https://opendatacharter.net/)
* _TODO: FAIR/CARE data checker? Arctic Data Center maybe has something like this. Ask?_
